version: '3'
services: 
  #build the dockerfile for the python image
  # db:
  #   container_name: mydb
  #   image: mysql:5.7
  #   ports:
  #       - "32001:3306"
  #   environment:
  #       MYSQL_ROOT_PASSWORD: root
  web:
    # links: 
    #   - "db"
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000